//
//  MatchRouter.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MatchRouterInput {
    func navigateToPlayer(player: Player)
    func navigateToGraph(matches: [Match])
}

class MatchRouter: MatchRouterInput {
    weak var viewController: MatchViewController!
    func navigateToPlayer(player: Player) {
        let controller = PlayerConfigurator.getController(player: player)
        self.viewController.navigationController?.pushViewController(controller, animated: true)
    }
    
    func navigateToGraph(matches: [Match]) {
        let controller = GraphConfigurator.getController(matches: matches)
        self.viewController.navigationController?.pushViewController(controller, animated: true)
    }
}
