//
//  MatchPresenter.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MatchPresenterInput {
}

protocol MatchPresenterOutput: class {
}

class MatchPresenter: MatchPresenterInput {
    weak var output: MatchPresenterOutput!
    
    // MARK: - Presentation logic
}
