//
//  MatchViewController.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MatchViewControllerInput {
    
}

protocol MatchViewControllerOutput {
    
}

class MatchViewController: BaseViewController, MatchViewControllerInput {
    var output: MatchViewControllerOutput!
    var router: MatchRouter!
    
    // MARK: - Object lifecycle
}
