//
//  MatchInteractor.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MatchInteractorInput {
    func load(request: MatchRequest)
}

protocol MatchInteractorOutput: ErrorPresenterInput {
    func present(response: MatchResponse)
}

class MatchInteractor: MatchInteractorInput {
    var output: MatchInteractorOutput!
    var repository: Repository!
    func load(request: MatchRequest) {
        self.repository
            .matchList()
            .startWithResult { [weak self] result in
                if let value = result.value {
                    self?.output.present(response: MatchResponse(matches: value))
                } else {
                    self?.output.presentError(error: "Cannot call service")
                }
        }
    }
}
