//
//  MatchPresenter.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MatchPresenterInput {
    func present(response: MatchResponse)
}

protocol MatchPresenterOutput: class {
    func display(viewModel: MatchViewModel)
}

class MatchPresenter: MatchPresenterInput {
    weak var output: MatchPresenterOutput!
    
    // MARK: - Presentation logic
    func present(response: MatchResponse) {
        let matches = response.matches
        
    }
}
