//
//  PlayerViewController.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlayerViewControllerInput {
}

protocol PlayerViewControllerOutput {
}

class PlayerViewController: BaseViewController, PlayerViewControllerInput {
    var output: PlayerViewControllerOutput!
    var router: PlayerRouter!
    
    // MARK: - Object lifecycle
    let player: Player!
    init(player: Player) {
        self.player = player
        super.init()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func configureSubviews() {
        super.configureSubviews()
        
    }
}
