//
//  PlayerViewController.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ReactiveCocoa
import ReactiveSwift
import BonMot
import EasyPeasy

protocol PlayerViewControllerInput {
    func display(viewModel: PlayerViewModel)
}

protocol PlayerViewControllerOutput {
    func load(request: PlayerRequest)
}

class PlayerViewController: BaseViewController, PlayerViewControllerInput {
    var output: PlayerViewControllerOutput!
    var router: PlayerRouter!
    
    // MARK: - Object lifecycle
    let playerView = PlayerView()
    var tableView = UITableView()
    var result = [SectionModel]()
    
    let player: Player!
    init(player: Player) {
        self.player = player
        super.init()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func configureSubviews() {
        super.configureSubviews()
        self.view.addSubview(self.playerView)
        self.view.addSubview(self.tableView)
        
        self.tableView.dataSource = self
        self.tableView.delegate = self
        self.tableView.rowHeight = UITableViewAutomaticDimension
        self.tableView.estimatedRowHeight = 140
        self.tableView.separatorStyle = .none
        self.tableView.allowsSelection = false
    }
    
    override func configureLayout() {
        super.configureLayout()
        self.playerView.easy.layout(
            Top().to(self.topLayoutGuide),
            Left(),
            Right()
        )
        self.tableView.easy.layout(
            Top().to(self.playerView, .bottom),
            Left(),
            Right(),
            Bottom()
        )
    }
    
    override func configureContent() {
        super.configureContent()
        self.showHUD()
        self.output.load(request: PlayerRequest(player: self.player))
        self.navigationItem.backBarButtonItem?.title = ""
    }
    
    override func tryAgainAction() {
        self.showHUD()
        self.output.load(request: PlayerRequest(player: self.player))
    }
    
    func display(viewModel: PlayerViewModel) {
        self.result.removeAll()
        self.playerView.configure(model: viewModel.playerModel)
        self.result.append(contentsOf: viewModel.list)
        self.tableView.reloadData()
    }
    
    override func navigationTitle() -> String {
        return self.player.shortName
    }
    
    override func shouldShowNavigationBar() -> Bool {
        return true
    }
}

extension PlayerViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let headerModel = result[section].header
        let view = HeaderView()
        view.configure(model: headerModel)
        return view
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return result.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return result[section].items.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let model = self.result[indexPath.section].items[indexPath.row]
        let cell = TitleAndDetailCell()
        cell.configure(model: model)        
        return cell
    }
}

extension PlayerViewController: UITableViewDelegate {
    
}
