//
//  PlayerPresenter.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlayerPresenterInput {
    func present(response: PlayerResponse)
}

protocol PlayerPresenterOutput: class {
    func display(viewModel: PlayerViewModel)
}

class PlayerPresenter: PlayerPresenterInput {
  weak var output: PlayerPresenterOutput!
  
  // MARK: - Presentation logic
    func present(response: PlayerResponse) {
        let detail = response.playerDetail
        let player = detail.player
        
        let playerModel = PlayerModel(player: player, style: PlayerModel.Style(imageSize: CGSize(width: 120, height: 200)))
        
        // go through each field in the model
    }
}
