//
//  PlayerModels.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/15/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct PlayerRequest {
    var player: Player
}

struct PlayerResponse {
    var playerDetail: PlayerDetail
}

class PlayerViewModel {
    var playerModel: PlayerModel
    var list: [HeaderModel]
    init(playerModel: PlayerModel, list: [HeaderModel]) {
        self.playerModel = playerModel
        self.list = list
    }
}
