//
//  GraphModels.swift
//  PlayerStat
//
//  Created by Le Thanh Hai on 11/19/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct GraphRequest {
    let matches: [Match]
}

struct GraphResponse {
    let matches: [Match]
}

class GraphViewModel {
    let list: [GraphSectionData]
    init(list: [GraphSectionData]) {
        self.list = list
    }
}

class GraphSectionData {
    let headerModel: HeaderModel
    let graphList: [AnyObject]
    init(headerModel: HeaderModel,
         graphList: [AnyObject]) {
        self.headerModel = headerModel
        self.graphList = graphList
    }
}
